### ISSUE TITLE
dropblock ？ 

### ISSUE THREAD

**Issue by wangzhongyu1997** [xiujuan-zhu/Zhu_AIAL-XJU_task4#1]
![image](https://user-images.githubusercontent.com/18252704/164731433-e9b9ed51-645a-4053-93cd-d60cad442c44.png)
这份代码用到 dropblock 了吗？这边没有实现。。。

**Comment by xiujuan-zhu** [comment]
本代码里面没有使用dropblock，具体实现的你可以参考这篇“Resnest: Split-attention networks”的代码实现哦!
